[workspace]
platforms = ["linux-64"]
channels = ["https://conda.modular.com/max-nightly", "https://prefix.dev/conda-forge", "https://conda.anaconda.org/nvidia"]

[system-requirements]
cuda = "12.0"
libc = "2.34"

[dependencies]
python = "==3.12.12"
pytorch-gpu = ">=2.8.0,<3"
modular = "==25.7"
beartype = ">=0.22.9,<0.23"

[pypi-dependencies]
nvitop = ">=1.5.3, <2"
